### PR TITLE
CONTROLLER: Intern Post

### PR DESCRIPTION
**Pull request by Pwongchaiya**

### CODE REVIEW

**Comment by hassanhabib** [comment]
Two things:
- Split ACCEPTANCE and CONTROLLER into two different PRs
- Post a screenshot from Postman/Swagger that shows the results

**Comment by Pwongchaiya** [comment]
Screenshot 2023-06-27 at 13-03-39 Swagger UI

**Comment by Pwongchaiya** [comment]
Screenshot 2023-06-27 at 13-03-39 Swagger UI

**Comment by Pwongchaiya** [comment]
Screenshot 2023-06-27 at 13-02-31 Swagger UI

**Pull request merged**
