### PR TITLE
CONTROLLER: Get All Interns

### PR DESCRIPTION
**Pull request by Pwongchaiya**

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
The commit history is bad. For this type of issue, we expect only one controller to be changed. Closing because of this reason

**Comment by hassanhabib** [comment]
@ElbekDeveloper I think he is only branching off of another one - let's see what this PR looks like after the base is merged. I will wait a minute.

**Comment by Pwongchaiya** [comment]
Screenshot 2023-06-29 at 16-20-17 Swagger UI

**Pull request closed without merging**
